name: everwatch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pyyaml
  - dask
  - distributed
  - pandas
  - rasterio
  - geopandas
  - shapely>=2.0
  - pytorch::pytorch
  - pytorch::torchvision
  - nvidia::cudatoolkit
  - bioconda::snakemake
  - opencv
  - pip:
      - git+https://github.com/weecology/DeepForest.git@main
      - dask_jobqueue
      - comet_ml
      - paramiko
      - slidingwindow
      - xmltodict
      - pytest
      - yapf
      - black
      - pytest-cov
      - pytest-xdist
      - pdoc
      - rio-mbtiles
      - boto3
